疲れている。

golang で err がネストしてしまったときや `defer` が使えないときの後処理をどうしようってなる。

```golang
func openTwoConnections() (*Con1, *Con2, error) {
  conn1, err := open1();
  if err != nil {
    return nil, nil, err
  }

  conn2, err := open2();
  if err != nil {
    // このへん
    if err2 := close1(conn1); err2 != nil {
      return nil, nil, err // err を返す or err2 を返す or 合わせた何かを返す
    }

    return nil, nil, err
  }

  return conn1, conn2, err
}
```

その関数の中で閉じて良いなら `defer conn1.Close()` みたいにしてしまうと良いんだろうけど……。

コールバックをとって `defer` するみたいな手もあるけど適用しづらい場面もあって……。

---

今日のコミット。

- [rust-sandbox](https://github.com/bouzuya/rust-sandbox) 1 commit
  - [iddd_a_and_es: 0.0.4](https://github.com/bouzuya/rust-sandbox/commit/30a64e15cea5b59514214b24254fa78f64050e02)
- [rust-atcoder](https://github.com/bouzuya/rust-atcoder) 1 commit
  - [donuts-live2014 a](https://github.com/bouzuya/rust-atcoder/commit/1afec6fa4b5fed3742fc488a89beaed2c3434263)
